### ISSUE TITLE
Ravil and Igor Lookalike graphics issue

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#274]
![doukutsu-v0 5 1a001](https://user-images.githubusercontent.com/36712090/38222631-c5f2c940-369a-11e8-8589-845042b66d94.jpg)
![doukutsu-v0 5 1a002](https://user-images.githubusercontent.com/36712090/38222637-caa12e96-369a-11e8-8896-f2aceb639ea9.jpg)

This happened during a test run that went beyond the screenshared runs. Only seemed to happen once.

**Comment by Leo40Git** [comment]
This used to happen when the Map System was used, but to my knowledge, that specific bug was fixed.

**Comment by SkyTheLeafeon** [comment]
This happened in 0.5.1a! @Leo40Git

**Comment by Leo40Git** [comment]
I said that specific bug was fixed, I didn't say anything about all graphical corruption being fixed.

**Comment by SkyTheLeafeon** [comment]
...Right.

**Comment by andwn** [comment]
Oh hey this still happens in 0.7.0 but fixed it now by converting Ravil to a sprite sheet. It was most likely because the helicopter is so big the VRAM memory allocation gets fragmented, and picks a spot that's already occupied by other NPCs.
