### ISSUE TITLE
Sprites sometimes show as whiteboxes

### ISSUE THREAD

**Issue by soniccd123** [andwn/cave-story-md#321]
Tested in real hardware, played the whole game and everything worked just fine, beautiful port by the way, but sometimes one or two sprites get corrupted. As i could notice, it seens to be just one frame of animation when it is on an animated objetc, other times is a droped item, some scrolling background, the weapon projectile sprites or a HUD element. Almost always is just one sprite that gets corrupted in the scene and it shows as a whitebox or garbage lines with the size of the sprite. Most of the time pausing and unpausing the game solves the problem, but not rarely a new sprite gets corrupted. Entering again a room or scene when theres a door available also fixes the corrupted sprites.

**Comment by andwn** [comment]
I think I know why this happened actually, forgot to do something that prevents an issue like this on some specific hardware models. Mind trying a patched ROM if I upload one here?

**Comment by soniccd123** [comment]
No problems! I'll happly test it and report back. If you need hardware specifics, i'm playing in a japanese Mega Drive model 1 (HAA-2510) with a 32X attached using a simples flashcart that i made (EPROM and FeRAM), i dont know exactly which motherboard revision, but if its important, i can look into it.

**Comment by andwn** [comment]
So yeah definitely forgot to pause the Z80 when doing DMA which can cause graphical issues. Don't remember which consoles it affects exactly but supposedly earlier model 1s are part of that group. Hopefully this build will fix that. If not, then maybe it isn't what I thought it was after all.

[doukutsu.bin.zip](https://github.com/andwn/cave-story-md/files/5019495/doukutsu.bin.zip)

**Comment by soniccd123** [comment]
Hello, i have tested Egg Corridor and Grasstown and the problem seen to be almost gone. I had just two situations where the HUD level bar became white and another one that the gun projectile became corrupted. I will play more later to see if theres more situations

**Comment by andwn** [comment]
Ok, at least I'm on the right track. I bet it's just that there are more places I use DMA to upload graphics and need to take care of those too.

Might need to find a Japanese model 1 one of these days, but don't know if all of them do this or just the earlier board revisions. The spritesmind folks probably know.

**Comment by andwn** [comment]
Oh, and thank you for confirming!

**Comment by mastercheff** [comment]
Hello, I have  a PAL Mega Drive VA6  modded for ntsc display, last couple of days i started playing this with version 0.6 , sprites were often corrupted. Now today checked the 0.7 release , its better : with fireball glitch is mostly gone , but still occurs on power triangles and enemy sprites... Otherwise, magnificent work Sir, I enjoy it a ton since genny/md lacked proper metroidvania

**Comment by mastercheff** [comment]
Yesterday i tinkered a bit with ROM supplied within this topic. There are noticeable differences in behavior: fireball projectiles are less glitchy, but instead rocket launcher trail is all white boxes. Also in 0.7 when You spam fireball while exiting a room, projectiles appear in the new room (in build of 4 august they stay in the room when You fired it and reappear correctly with quick re-entering). The area I focused on is Labirynth W,H

**Comment by andwn** [comment]
I think the white boxes are because I forgot to pause the z80 when loading sprite sheets during map load. That other thing your are describing is something different. I think the bullet array just needs to be cleared when the room loads too.

**Comment by mastercheff** [comment]
Aye, thanks for responding - now I know the overlord is watching this, thumbs up and fingers crossed. I'm realtively fresh to the mega drive. Gunstar Heroes will keep me occupied for now :)

**Comment by nor2101** [comment]
I'd like to add my two cents. I have a PAL Mega Drive Model 1 VA6 with selectable dual main system oscillators and region/language switch. I play the game (v0.7.0) in NTSC mode, and while it works flawlessy most of the time, I have the same graphical glitches described here. I have not tested in PAL mode yet.

**Comment by mastercheff** [comment]
I got around this annoyance with pausing and unpausing the game, clears right up (0.7)

**Comment by mastercheff** [comment]
Hi I've seen there's been some progress lately, @andwn  Would You consider an insider build to fool around? ( Yes I have bought Dezatopia and Mecha Ritz on Steam  to show my support :) ) . Just yesterday I recieved new and fresh 8bitdo m30 gamepad , would love to jump in right into CS cheers

**Comment by andwn** [comment]
I was paid a flat sum to work on those lol. Here's what's currently in my build folder though:
[doukutsu-20220118.zip](https://github.com/andwn/cave-story-md/files/7946603/doukutsu-20220118.zip)

Expect something to be broken somewhere I haven't even played past Egg Corridor, apart from testing random places from level select.

**Comment by mastercheff** [comment]
Thanks a lot sir, I played this build for some time yesterday, managed to get from waterway to the final boss -normal ending. The whiteboxes bug is mostly gone , visual corruption now  happens on the outside edge of dialogue box (not always) , parallax clouds in outer wall area (minor) and water effects in waterway 

https://share.icloud.com/photos/0afB4Aq_nWK0eRVa7yj1uPy0w

Overall it's much improved, and a blast to play

**Comment by andwn** [comment]
Yeah, the water tiles were being uploaded to the wrong place after I un-split the tiles, that was my mistake not a hardware issue luckily.

**Comment by mastercheff** [comment]
will try to dig some more when I have the time (it's working weekend for me - little or no time for gaming)

**Comment by mastercheff** [comment]
Today I started fresh from the beginning, aside from egg corridor background wonkiness (photo), it's all good zero issues all through sand zone so far

https://share.icloud.com/photos/0c86LVVAJSHpVoAiuBMPTz_3g

sometimes (outro sequence with kazuma and clouds) textbox outline blends well, in other instances it's not coherent, and occasional blinking but You may be well aware of it. If You accept PP donations I'm eager to throw some $ it's my favourite mega drive homebrew

**Comment by andwn** [comment]
Yep, turns out I wasn't stopping the Z80 when loading the backgrounds and credits images still...

The window thing is just kind of the way it is. The window layer overlaps the layer the map gets drawn on. I was considering changing the border to be flat instead of a zigzag in order to hide it.

**Comment by mastercheff** [comment]
latest batch of glitchizz

https://share.icloud.com/photos/01axvFonGgmtm6fK8diXcIaQg

I made a de-facto full run of the game, off the mecha-x boss to the normal ending, then starting fresh now in outer wall. No bloodstained sanctuary yet, stupid me did get Booster v0.8  ( the pun )

**Comment by andwn** [comment]
Trying something with the window now. Made the border flat to hide the overlap. Most of those graphical issues with the backgrounds/tiles should also be fixed.

[doukutsu-en.bin.zip](https://github.com/andwn/cave-story-md/files/7973501/doukutsu-en.bin.zip)

**Comment by Darknior** [comment]
WOAW excellent, you have fixed so many problems :)
The last version 0.7.0 from 2020 is really old ... will you release a new official beta version ?
Thanks a lot

**Comment by mastercheff** [comment]
I can feel the 1.0 is around the corner , 2.2.22 perhaps ? In other news, i swapped 8bitdo m30 dpad membrane for genuine saturn one it fits snug - less stiff, better diagonals

**Comment by mastercheff** [comment]
One more thing. I like the way MD/GEN renders this at 60hz 240p. In other versions (recent ps1, original freeware pc game , xbox port) running the game at 60 hz ruins fluidity, game was supposed to run 50. In THIS version it's much better or GENESIS DOES

**Comment by mastercheff** [comment]
https://share.icloud.com/photos/061-1Ta66Jv0dBVAiwzcyq0zA

first one was pretty epic. i spammed pause unpause with map X button (plantation area), rendering takes a while, it started glitching for about 20 seconds with different colors and patterns than stopped on whats in the photo. all footage from 31.1 test build

**Comment by andwn** [comment]
Here's an attempt to fix the map thing. 

[doukutsu-en.bin.zip](https://github.com/andwn/cave-story-md/files/7977059/doukutsu-en.bin.zip)

**Comment by mastercheff** [comment]
map glitch is fixed,  confirmed.  Corruption on HP bar first slot save file persists on every bootup (even soft reset doesn't help)

**Comment by mastercheff** [comment]
rn, a softlock

https://share.icloud.com/photos/091Wstld6SHvaRLxM6JGpFaWw

after beating monster X , without using Clinic Key first

**Comment by mastercheff** [comment]
yes invisible wall ... made another lap  to sand zone , 0 glitches so far . and finally fired up sanctuary via cheatcode 🥇 running great

**Comment by mastercheff** [comment]
https://share.icloud.com/photos/0c6RQzqabmJRi8iwL4xcpYI_Q

Text window is acceptable now even with water layer.
With the level select I made it through the core fight without issues, water current on the other hand... further testing in ~18 hrs

Be safe from the dreaded lurgy

**Comment by andwn** [comment]
Ok this should fix the Monster X barrier and save select.

[doukutsu-en.bin.zip](https://github.com/andwn/cave-story-md/files/7986121/doukutsu-en.bin.zip)

**Comment by mastercheff** [comment]
barrier still persists, and some fresh buggies

https://share.icloud.com/photos/060WpXsZMQfWV2cLogoTTSG0Q

after work I will sit down with level select and the 1.02.22 build it just happens to be the most stable

**Comment by andwn** [comment]
I dunno I fought Monster X a couple times and could leave the arena without any invisible barriers stopping me after making those changes. Maybe I uploaded the wrong file?

[doukutsu-en.bin.zip](https://github.com/andwn/cave-story-md/files/7987580/doukutsu-en.bin.zip)

**Comment by mastercheff** [comment]
monster x barrier - fixed
save file select - fixed

will report later on water current and late game bosses

**Comment by mastercheff** [comment]
https://www.icloud.com/photos/#080kJK5W6Ie_HmW22-Uw2fpVA

only happened early in the session -rockets  and also late into it (took me over 1h to plantation ) weapons changing randomly on right/left footstep, with audio buzzing too

no incidents on bossfights ,  only slightly audio hanging when entering certain doors (Labirynth M, Waterway) 

is it damn You Zilog ;) situation or just limited memory ? 

if it's too much feedback and/or headache for You, I can slow down obviously :)

**Comment by mastercheff** [comment]
https://share.icloud.com/photos/05eHr8alnuxo-Uvh79azJKFlA

Fresh run from the beginning. First balrog didn't spawn or collapsed through the floor ( had my thumb on A button pressed - might have missed it) reset helped. Smooth sailing until frog boss when fireball lv.3 didnt render its trail (pic). After that it was glitch free until Waterway.  I stopped in plantation, will report on *luckily* both endings soon

As of right now it's beat the game edition again, which is super dope imho 👍

**Comment by mastercheff** [comment]
![barrier2](https://user-images.githubusercontent.com/60203533/152617547-7306e7f6-9560-45ae-b80a-308b28bfd12b.png)

another invisible barrier is in the last cave :)

**Comment by andwn** [comment]
Ok this one should fix Balrog and those barriers. At least it did for me but "reset worked" has me wondering.

[doukutsu-en.bin.zip](https://github.com/andwn/cave-story-md/files/8008953/doukutsu-en.bin.zip)

**Comment by mastercheff** [comment]
The only weirdness i encountered while doing ma pignon sequence

![void](https://user-images.githubusercontent.com/60203533/152664049-d39add91-d971-4466-a02d-16e6f521b3e7.png)

BOTH ENDINGS WORK

**Comment by andwn** [comment]
And now why the hell does the room with water hang for 5-10 seconds drawing the background over and over again. What did I even do

**Comment by mastercheff** [comment]
Well thats a bummer... The only console i own is a model 1  VA6 pal megadrive (deliberate choice - better sound)...

thing is, all of retail games i throw at it - ntsc jap/us work without a hiccup. Some homebrew efforts like the recent Megaman sequel wars (last demo with 5 levels) give similar visual glitches to csmd (before recent changes) I hope i didn't screw Your project too much

Had to take day off with testing, will do another playthrough

**Comment by andwn** [comment]
I actually figured out the water background thing last night. The code that updates the background tiles based on the water position ran before the object containing the water position existed (bad pointer) so the value was some random garbage.

**Comment by mastercheff** [comment]
Some time in the future I plan to mod the console with 50/60hz switch, playstation cave story (https://github.com/fgsfdsfgs/doukutsupsx) runs much much better in pal mode indeed

as for CSMD i plan to do some casual runs in the upcoming days. Yesterday's run was all cutscenes on fast forward button, the only one that glitched is the first balrog

**Comment by andwn** [comment]
Yeah, still not sure how fast forward is messing up those cutscenes in particular. Might have to do with Balrog falling while the text box is filling up, and instantly skipping it makes the "Balrog dropping" object change to the normal Balrog object too early. Will figure something out for those in one of my next bouts of free time.

**Comment by mastercheff** [comment]
I did 100% of content lately, so here goes

https://share.icloud.com/photos/05b_VDfwpF5W7_QAOQAL2dRGA

nemesis weapon has problems shooting up and down, shooting L/R is is clear of corrupted sprites  (strangely, when doing sanctuary with Curly it rendered OK up if I remember correctly)
otherwise, except waterway it's ready to next major release imho

**Comment by andwn** [comment]
A junk shop in Akiba happened to have a couple VA0s in stock so I'm now a proud owner of this disasterpiece. Going to try and do most of my testing on it from now on and catch any more places where I forget to stop the Z80 before DMA causing the white boxes.
